

name: CI C

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x64
          - x86
    steps:
      - uses: actions/checkout@v4
      # - uses: ilammy/msvc-dev-cmd@v1
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: ${{ matrix.arch }}
      - name: Compile
        run: clang.exe -o main.exe main.c
      - name: Test
        run: ./main.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./*.exe
