

name: CI C

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # - uses: actions/checkout@v4
      # - uses: ilammy/msvc-dev-cmd@v1
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - name: Build something requiring CL.EXE
        run: |
          "%VS140COMNTOOLS%../../VC/vcvarsall.bat" x64
          cl.exe main.c
          main.exe
