name: CI C

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: ilammy/msvc-dev-cmd@v1
      # - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - name: Env 
        run: |
          pwd
          dir
      - name: Env pwd
        run: pwd
      - name: Env dir
        run: dir
      - name: Compile
        run: clang.exe -o main.exe main.c
      - name: Test
        run: ./main.exe | Out-File -FilePath $env:GITHUB_ENV -Append 
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./*.exe
